language: swift
xcode_workspace: DOProject/DOProject.xcodeproj
xcode_scheme: DOProjectTests
xcode_sdk: iphonesimulator
env: CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO
notifications:
  email: thuongvuhuu@gmail.com
